### ISSUE TITLE
Links is incorrect

### ISSUE THREAD

**Issue by Reto9lxOne** [RimRexWorld/Language-Script#2]
The Link to the XML file is incorrect and will download an html File.
Please chance it to: https://raw.githubusercontent.com/RimRexWorld/Language-Script/main/ch-Region.xml

With love from Mägenwil ;-)

**Comment by RimRexWorld** [comment]
Thank you for reporting the issue.
Please try now with the new Script and have fun!

Made with love in India... öh in Wallis :D

**Comment by RimRexWorld** [comment]
File URL has been changed to https://raw.githubusercontent.com/RimRexWorld/Language-Script/main/ch-Region.xml
